[package]
name = "rust_sandbox"
version = "0.1.0"
author = ["J Mathew <joshkmatt@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]